spring:
  profiles:
    active: local


spring.batch.job.names: ${job.name:NONE}

tmdb:
  baseUrl: https://api.themoviedb.org/3
  apiKey: 0b1fe3786795a257dd0648d67445af97
---
spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver

tmdb:
  baseUrl: https://api.themoviedb.org/3
  apiKey: 0b1fe3786795a257dd0648d67445af97
---
spring:
  profiles: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/spring_batch?characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create

tmdb:
  baseUrl: https://api.themoviedb.org/3
  apiKey: 0b1fe3786795a257dd0648d67445af97